config/routes.rb
Foundr::Application.routes.draw do
  root :to => 'application#find_root_url'
  resources :roles do
    resources :profiles
    collection do
      get 'login'
      post 'login'
      post 'authenticate'
      get   'search'
      post  'search'
      get 'refresh'
      post 'refresh'
    end
  end
  resources :profiles
  resources :ambitions

  post 'roles/login' => 'roles#login'
  get 'roles/login' => 'roles#login'
  get 'roles/signup' => 'roles#signup'
  post 'roles/signup' => 'roles#signup'
  post 'roles/authenticate' => 'roles#authenticate'
  post 'roles/logout' => 'roles#logout'
  get 'roles/search' => 'roles#search'
  post 'roles/search' => 'roles#search'
  get 'tags/:tag', to: 'roles#index', as: :tag
end

app/views/shared/_footer.html.erb
<footer>
<div class="container">
	copyright gradesnap llc 2012 
</div>
</footer>

app/views/shared/_geolocate.html.erb
<div class="searchForm">
    <div class="field">
      <%= label_tag :ambition_ids, "Ambitions" %>
      <% @ambitions = Ambition.all %>
      <% @ambitions.each do |ambition| %>
        <br />
        <%= label_tag "ambitions[#{ambition.id}]", ambition.name %>
        <%= check_box_tag "ambitions[#{ambition.id}]", ambition.name %>
        <br />
      <% end %>
    </div>

    <br />
    <div class="field">
      <%= label_tag :tag_list, "Skills (separated by commas)" %>
      <%= text_field_tag :tag_list %>
    </div>
</div>
<div class="nycBack">
<div class="container">
<button class="button" onClick="getLocation()">Load more users</button>

<script>

	var lim = 0
	var max_dist = 0
	// Call getLocation when the page loads
	$(document).ready(getLocation)

	var x=document.getElementById("demo");
	function getLocation()
	  {
	  if (navigator.geolocation)
	    {
	    navigator.geolocation.getCurrentPosition(refreshCall,showError);
	    }
	  else{x.innerHTML="Geolocation is not supported by this browser.";}
	  }
	function showError(error)
	  {
	  switch(error.code) 
	    {
	    case error.PERMISSION_DENIED:
	      x.innerHTML="User denied the request for Geolocation."
	      break;
	    case error.POSITION_UNAVAILABLE:
	      x.innerHTML="Location information is unavailable."
	      break;
	    case error.TIMEOUT:
	      x.innerHTML="The request to get user location timed out."
	      break;
	    case error.UNKNOWN_ERROR:
	      x.innerHTML="An unknown error occurred."
	      break;
	    }
	  }

	  /**
	   * ajax call with limit and distance to load role partial
	   * -> each call increments LIMIT by 20 and DISTANCE by 2km and calls again
	  **/
	  function refreshCall(position)
	  {
	  	if (max_dist < 15) {
	  		max_dist += 5;
	  	}
	  	lim += 20

	  	// Ambition ids: stored as a comma-separated string
	  	var amb_ids = "";
	  	var ambition_id = "";
	  	/*
	  	for ( var i = 0; i < <%= @ambitions.length %>; i++ ) {	
	  		// TODO get this line to work (for some reason, .checked breaks everything)
	  		ambition_id = "ambitions_" + i.toString();
	  		var ambition_box = document.getElementById(ambition_id);
	  		if (ambition_box.checked){
	  			amb_ids = amb_ids + i.toString() + ",";
	  		}
	  	}
		*/
	  	// Taglist: stored as comma-separated string
	  	var taglist = document.getElementById("tag_list").value;

	  	"<% @roles = [] %>"
	  	$.ajax({ type: "POST", url: "<%= role_refresh_path %>", data: { limit: lim, max_distance: max_dist, latitude: position.coords.latitude, longitude: position.coords.longitude, ambition_ids: amb_ids, tag_list: taglist }
	  			}).done(function(html) {
	  				$(".role").empty();
	  				$(".role").append(html);
	  			});
	  }

</script>

app/views/shared/_navbar.html.erb
<div class="myNav">
  <div class="container">
    <% unless session[:role_id].nil? %>
    <!-- Logged in -->
  <ul>
    <li><%= link_to "Foundr", role_index_path, :class =>
    'brand' %></li>
      <li>
        <%= link_to "My Profile", :action =>"show", :controller => "roles", :id => session[:role_id] %></li>
      <li>
        <%= link_to "Edit Profile", :action =>"edit", :controller => "roles", :id => session[:role_id] %></li>
      <li>
        <%= link_to "Logout", role_logout_path, :method =>:logout %></li>
    </ul>
    <!-- /Logged in -->

    <% else %>
    <!-- NOT Logged in -->
        <ul>
    <li><%= link_to "Foundr", role_login_path, :class =>
    'brand', :method => :login %></li>
      <li>
        <%= link_to "Sign in", role_login_path, :method =>:login %></li>
      <li><a id="signToggle">Sign Up</a></li>
    </ul>
    <!-- /NOT logged in -->
    <% end %></div>
</div>