config/routes.rb
Foundr::Application.routes.draw do
  root :to => 'application#find_root_url'
  resources :roles do
    resources :profiles
    collection do
      get 'login'
      post 'login'
      post 'authenticate'
      get   'search'
      post  'search'
      get 'refresh'
      post 'refresh'
    end
  end
  resources :profiles
  resources :ambitions

  post 'roles/login' => 'roles#login'
  get 'roles/login' => 'roles#login'
  get 'roles/signup' => 'roles#signup'
  post 'roles/signup' => 'roles#signup'
  post 'roles/authenticate' => 'roles#authenticate'
  post 'roles/logout' => 'roles#logout'
  get 'roles/search' => 'roles#search'
  post 'roles/search' => 'roles#search'
  get 'tags/:tag', to: 'roles#index', as: :tag
end

app/models/role.rb
class Role < ActiveRecord::Base
    mount_uploader :picture, PictureUploader
    attr_accessible :picture

    EMAIL_MINIMUM_LENGTH = 8
    EMAIL_MAXIMUM_LENGTH = 32

    EMAIL_FORMAT = /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i

    PASSWORD_MINIMUM_LENGTH = 8
    PASSWORD_MAXIMUM_LENGTH = 64

    EMAIL_PRESENCE_MESSAGE = "email is a required field"
    EMAIL_UNIQUENESS_MESSAGE = "email is already taken"
    EMAIL_LENGTH_MESSAGE = "email must be between %i and %i characters" %
                                   [ EMAIL_MINIMUM_LENGTH, EMAIL_MAXIMUM_LENGTH ]
    
    EMAIL_FORMAT_MESSAGE = "email must follow the given format: name@host.domain"

    PASSWORD_LENGTH_MESSAGE = "password must be between %i and %i characters" %
                            [ PASSWORD_MINIMUM_LENGTH, PASSWORD_MAXIMUM_LENGTH]

    CONFIRM_PASSWORD_MESSAGE = "passwords do not match"

    attr_accessible :email, :password, :password_confirm, :profile_id, :profile_attributes

    attr_accessor :password_confirm

    has_one :profile
    has_one :geolocation
    accepts_nested_attributes_for :geolocation
    accepts_nested_attributes_for :profile

    validates :email, :presence => { :message => EMAIL_PRESENCE_MESSAGE }
    validates :email, :uniqueness => { :message => EMAIL_UNIQUENESS_MESSAGE }
    validates :email, :length => { :minimum => EMAIL_MINIMUM_LENGTH,
                                  :maximum => EMAIL_MAXIMUM_LENGTH,
                                  :message => EMAIL_LENGTH_MESSAGE }
    validates :email, :format => { :with => EMAIL_FORMAT,
                                  :message => EMAIL_FORMAT_MESSAGE }

    validates :password, :length => { :minimum => PASSWORD_MINIMUM_LENGTH,
                                      :maximum => PASSWORD_MAXIMUM_LENGTH,
                                      :message => PASSWORD_LENGTH_MESSAGE },
                         :allow_nil => true

    validate :confirm_password, :unless => :password_nil?

    before_save { |role| role.email = role.email.downcase }

    def self.authenticate( email, password )
        role = find_by_email( email )    
        if role
            Rails.logger.info("PASS - ME: #{password}")
            Rails.logger.info("PASS - DB: #{role.password}")
            Rails.logger.info("PASS - ME DIGEST: #{Role.digest(password)}")
            Rails.logger.info("PASS - DB DIGEST: #{Role.digest(role.password)}")            
        end
        if role and role.password == Role.digest( password )
            role
        else
            nil
        end 
    end

    def encrypt_password
        self.password = Role.digest( password )
    end

private

    def password_nil?
        password.nil?
    end

    def confirm_password
        if password != Role.digest( password_confirm )
            if password != password_confirm
                errors.add( :password, CONFIRM_PASSWORD_MESSAGE )
            end
        end
    end

    def self.digest( source )
        Digest::SHA2.base64digest( source )
    end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
    before_filter :filter_authenticated, :only => [ :index,
                                                    :new,
                                                    :show,
                                                    :edit,
                                                    :create,
                                                    :update,
                                                    :destroy,
                                                    :logout,
                                                    :search,
                                                    :refresh ]
    before_filter :filter_unauthenticated, :only => [ :login,
                                                      :authenticate,
                                                      :signup,
                                                      :signup_post ]
    before_filter :find_role, :only => [ :show,
                                         :edit,
                                         :update,
                                         :destroy ]

    def refresh
        geoloc = Geolocation.where("role_id=?",session[:role_id]).first
        Geolocation.update(geoloc.id, :latitude => params[:latitude],
                                      :longitude => params[:longitude])     
        @roles = Geolocation.nearest_roles(params[:limit],
                                            params[:max_distance],
                                            params[:ambition_ids],
                                            params[:tag_list],
                                            session[:role_id])
        render :partial => 'role', :layout => false, :locals => { :roles => @roles }
    end

    def new
        @role = Role.new
    end

    def create
        @role = Role.new( params[:role] )
        if @role.save!
            redirect_to :action => :index
        else
            redirect_to :action => :login
        end
    end

    def update
        if @role.update_attributes( params[:role] )
            redirect_to :action => :show
        else
            render :action => :edit
        end
    end

    def destroy
        @role.destroy
        redirect_to :action => :index
    end

    def signup
        if params.has_key? :role
            @role = Role.new( params[:role] )
            @role.build_profile(:about => "", :headline => "", :name => "")
            @role.build_geolocation(:latitude => 0.0, :longitude => 0.0, :role_id => @role.id)
            if @role.save
                @role.encrypt_password
                @role.save!
                self.role_current = @role
                redirect_to :action => :index
            else
                redirect_to :action => :login
            end
        else
            @role = Role.new
        end
    end

    def logout
        role_unauthenticate
        redirect_to :action => :login, :method => :login
    end

    def authenticate
        if role_authenticate( params[:email].downcase, params[:password] )
            redirect_to :action => :index
        else
            redirect_to :action => :login
        end
    end

    def login
        if role_authenticated?
            redirect_to :action => "index", :controller => "roles"
        end
    end


private

    def find_role
        @role = Role.find( params[:id] )
    end

end

app/helpers/roles_helper.rb
module RolesHelper
    def role_login_path
        url_for :controller => :roles,
                :action => :login
    end

    def role_logout_path
        url_for :controller => :roles,
                :action => :logout
    end

    def role_authenticate_path
        url_for :controller => :roles,
                :action => :authenticate
    end

    def role_signup_path
        url_for :controller => :roles,
                :action => :signup
    end

    def role_index_path
        url_for :controller => :roles,
                :action => :index
    end

    def role_search_path
        url_for :controller => :roles,
                :action => :search
    end

    def role_refresh_path
        url_for :controller => :roles,
                :action => :refresh
    end
    
end

app/views/roles/_about.html.erb
Finding the right co-founder can be rough.  They have to be someone you can get along with and trust no matter how bad things get.  For every one right person there can be a hundred washouts, and the long search is a huge drain on time when your startup should be at the next stages yesterday.

Foundr helps you find potential business partners nearby.  No useless lengthy profiles, no BS fees, just people looking to do something amazing.  You in?

app/views/roles/_form-edit.html.erb
<%= simple_form_for @role do |f| %>

  <div class="field">
    <%= image_tag(@role.picture_url) if @role.picture? %>
    <%= f.label :picture, :label => "Profile Picture" %>
    <%= f.file_field :picture, :as => "Profile Picture", :label => "Profile Picture" %>
  </div>

  <%= f.simple_fields_for :profile do |profile| %>
    <fieldset>
      <div class="field">
        <%= profile.input :name %>
      </div>
    </fieldset>

    <fieldset>
      <div class="field">
        <%= profile.input :headline %>
      </div>
    </fieldset>

    <fieldset>
      <div class="field">
        <%= profile.input :about, :input_html => {:maxlength => 140, :size => 100 } %>
      </div>
    </fieldset>

    <fieldset>
      <div class="field">
        <%= profile.association :ambitions, :as => :check_boxes %>
      </div>
    </fieldset>

    <fieldset>
      <div class="field">
        <%= profile.input :tag_list, :size => 150, :label => "Skills (separated by commas)" %>
      </div>
    </fieldset>

  <% end %>

  <div class="field">
    <%= f.input :email, :required => false %>
  </div>

  <%= f.hidden_field :password, :value => @role.password  %>
  <%= f.hidden_field :password_confirm, :value => @role.password %>

  <div class="actions">
    <%= f.button :submit, :as => "Update profile", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/roles/_form.html.erb
<%= form_for @role = Role.new, :url => role_signup_path  do |f| %>
    <% if @role.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize( @role.errors.count, "error" ) %>
                                    prohibited this role from being saved:</h2>
            <ul>
                <% @role.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.text_field :email, :placeholder => "Email" %>
    </div>
    <div class="field">
        <%= f.password_field :password, :placeholder => "Password" %>
    </div>
    <div class="field">
        <%= f.password_field :password_confirm, :placeholder => "Password confirmation" %>
    </div>
    <div class="action">
        <%= f.submit "Sign up for Foundr", :class => "button" %>
    </div>
<% end %>

app/views/roles/_login_form.html.erb
<%= form_tag role_authenticate_path, :method => :post do %>
    <div class="field">
        <%= text_field_tag :email, nil, :placeholder => "Email" %>
    </div>
    <div class="field">
        <%= password_field_tag :password, nil, :placeholder => "Password" %>
    </div>
    <div class="actions">
        <%= submit_tag "Sign in", :class => "button" %>
    </div>
<% end %>

app/views/roles/_role.html.erb
<div class="tableWrapper">
<div class="role">
	<table class="table">
	<% count = 0 %>
	<% if @roles %>
		<% @roles.each do |role| %>
		  <%= "<tr class=userRow>".html_safe if count % 4 == 0 %>
		  <%= "</tr>".html_safe if count % 4 == 4 %>
		    <td class="userData"><small><%= link_to "#{role.profile.name}", :action => "show", :controller => "roles", :id => role.id %></small>
		    	<% if role.picture? %>
		    		<%= image_tag role.picture_url(:thumb) %>
		    	<% else %>
		    		<img src="http://placehold.it/80x80", class="img-rounded"></img></td>
		    	<% end %>
		  <% count = count + 1 %>
		<% end %>
	<% end %>
	</table>
</div>
</div>

app/views/roles/_search.html.erb
<div class="searchForm">
  <%#= form_tag role_search_path, :method => :post do %>

    <div class="field">
      <%= label_tag :ambition_ids, "Ambitions" %>
      <% @ambitions = Ambition.all %>
      <% @ambitions.each do |ambition| %>
        <br />
        <%= label_tag "ambitions[#{ambition.id}]", ambition.name %>
        <%= check_box_tag "ambitions[#{ambition.id}]", ambition.name %>
        <br />
      <% end %>
    </div>

    <script>
    var numAmbitions = <%= @ambitions.length %>
    </script>

    <br />
    <div class="field">
      <%= label_tag :tag_list, "Skills (separated by commas)" %>
      <%= text_field_tag :tag_list %>
    </div>

  <%# end %>
</div>

app/views/roles/edit.html.erb
<%= render 'form-edit' %>

app/views/roles/index.html.erb
<%= render :partial => 'shared/geolocate' %>

<%= render :partial => 'role' %>

app/views/roles/login.html.erb
<!-- leave container in each file, not application/layouts -->
<div class="nycBack">
	<div class="container">
		<div class="loginBox pull-right">
			<p class="largeText">Find your <span>dream</span> team</p>
			<p class="midText">
				Find and meet entrepreneurs, professionals, and innovators near you.
			</p>
			<p class="smallText">Sign in to Foundr</p>

			<div class="loginPartial">
				<%= render :partial =>'login_form' %></div>

			<!-- twitter bitch -->
			<a href="https://twitter.com/foundrapp" class="twitter-follow-button" data-show-count="false">Follow @foundrapp</a>
			<script>
	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
</script>
		</div>
		<div class="logo"></div>


	<%= render :partial =>'form' %>

<script>
$("#signToggle").click(function () {
$("#signIn").toggle(200);
});    
</script>
	</div>
</div>

<div class="container">
	<div class="upper">
		<div class="row">
			<div class="span6">
				<p class="headerText">find your dream team {now}</p>
				<p class="midText top30">finding like minded professionals in your area has never been easier</p>
			</div>
		</div>
	</div>
	<div class="about">
		<div class="row">
			<div class="span6">
				<p>Nam tortor metus, dapibus at pellentesque in, malesuada quis mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet justo a nulla viverra volutpat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce sed nibh sed lacus ultricies consequat sit amet iaculis dui.
			</div>
				<div class="span6">
				<p>Nam tortor metus, dapibus at pellentesque in, malesuada quis mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				</p>
				<p class="top20"><%= link_to "signing up is easy, and free", role_signup_path, :method =>:signup, :class => "button" %></p>
			</div>
	</div>
</div>
<%= render :partial => 'shared/footer' %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form', :url=> { :action => :create } %>

<%= link_to 'Back', roles_path %>

app/views/roles/privacy.html.erb
Privacy Policy

What information do we collect?

> We collect information when you register on our site, fill out a form, and upload files

> When you register: we may collect your name and email address

> When you register for our service, as appropriate, you may be asked to enter your: name or e-mail address.

> We use analytics software to track the number of viewers on our site. So long as you input no information, we have no information about you personally.

> We collect your geographic coordinates when you log in

> We reserve the right to track sessions while you're logged in, which may include IP address, email address, and timestamps. Sessions are provided thirty minutes of idle time (no requests made from the user of the session to our website) before you are automatically logged off, for safety reasons.

What do we use this information for?

Any of the information we collect from you may be used in one of the following ways:

> To personalize your experience (ex: display email address)

> To match users closest to you via geolocation

> To improve our website (we continually improve our site and its offerings based on the feedback and information we receive from you)

> To improve customer service (your information helps is better respond to your customer service and support needs)

> To securely process transactions

Foundr will never sell, exchange, trade, or transfer to any other given to any other company or institution your personally identifiable information, without your consent, except in the case of a court order, or health or safety emergency of the student or anyone at the school (if applicable).

> To send periodic emails

The email address you provide to register may be used to send you information and updates pertaining to Foundr, in addition to receiving occasional company news, updates, related product or service information, etc.

Note: If at any time you would like to unsubscribe from receiving future emails (sent on a subscription - not personal - basis), we include detailed unsubscribe instructions at the bottom of each email.

Foundr also respects the privacy of communication and gives its customers the option to receive periodic messages. A customer may change their setting at any time.

How do we protect your information?

Foundr uses industry standard security measures to protect your information.

We implement a variety of security measures to maintain the safety of your personal information when you access it, including (but not limited to) password hashing, cloud hosting in secure datacenters, etc.

Do we disclose any information to outside parties?

We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our policies, or protect our or others' rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.

Third party links

Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.

Online Privacy Policy Only

This online privacy policy applies only to information collected through our website and not to information collected offline.

Contacting Us

If there are any questions regarding this privacy policy you may contact us using the information below

http://www.foundr.com

125 Tech Park Drive

Rochester, NY 14623

USA

nikko.schaff@gmail.com

app/views/roles/show.html.erb
<div class="show-picture">
	<p><%= image_tag @role.picture_url if @role.picture? %></p>
</div>

<div class="show-info-basic">
	<div class="show-name">
		<p class="show-info">
		  <%= @role.profile.name %>
		</p>
	</div>

	<div class="show-distance">
		<p class="show-info">
		  <%= Geolocation.haversine_distance( session[:role_id], @role.id ) %> miles away
		</p>
	</div>

	<div class="show-email">
		  <p class="show-info">
		  	<%= @role.email %>
		  </p>
	</div>

	<div class="show-ambitions">
		<p>
			<strong>Ambitions:</strong>
		  <p class="show-info">
		  	<% @role.profile.ambitions.each do |ambition| %>
		  		<%= ambition.name %>
		  		<% unless ambition == @role.profile.ambitions.last %>
		  		,
		  		<% end %>
		  	<% end %>
		  </p>
		</p>
	</div>

	<div class="show-skills">
		<p>
			<strong>Skills:</strong>
		  <p class="show-info">
		  	<%= @role.profile.tag_list %>
		  </p>
		</p>
	</div>

</div>


<div class="show-info-descriptive">

	<div class="show-headline">
		<p>
		  <h4 class="show-headline">
		  	<%= @role.profile.headline %>
		  </h4>
		</p>
	</div>

	<div class="show-about">
		<p>
		  <p class="show-info">
		  	<%= @role.profile.about %>
		  </p>
		</p>
	</div>

</div>

app/views/roles/signup.html.erb
<div class="nycBack">
	<div class="container">
		<h1 class="login-header">Find your dream team</h1>
			<p class="login-text">Find and meet entrepreneurs, professionals, and innovators near you.</p>
			<h3 class="signup-header">Sign up for Foundr</h3>
			<%= render 'form', :url => role_signup_path %>

</div>
</div>